name: SCA - pip-audit

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  pip-audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Instalar pip-audit
        run: |
          python -m pip install --upgrade pip
          pip install pip-audit

      # Aqui ele analisa o arquivo com dependências vulneráveis
      - name: Rodar pip-audit (requirements_vulnerable.txt)
        run: |
          pip-audit -r requirements_vulnerable.txt || true

      # Opcional: comparar com as dependências "corrigidas"
      - name: Rodar pip-audit (requirements_fixed.txt)
        run: |
          pip-audit -r requirements_fixed.txt || true
